import Head from 'next/head'
import Image from 'next/image'
import usePostalCodeApi from '../hooks/postalCodeApi.ts'
import styles from './styles/Home.module.css'

export default function Home() {
  console.dir(usePostalCodeApi);
  return (
    <div className={styles.container}>
      <Head>
        <title>nextjs-typescript-api-client-sample</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>

        <p className={styles.postalcode}>
          <input type="text" placeholder="Please fill in your postal codes" name="postal-code" autoComplete="postal-code" />
        </p>

        <p className={styles.requestButton}>
          <input type="button" name="requestFromCodes" value="Get an address by your code" />
        </p>

      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
